### ISSUE TITLE
Data Provider Examples Need to be Updated

### ISSUE THREAD

**Issue by thetjhaze** [AdobeDocs/target-learn.en#1]
Issue in ./help/integrations/implement-data-providers-to-integrate-third-party-data.md

Hi - the examples in and around this page, including the videos, are for 1.3.  These examples do not work with 2.0 and need to be updated.

**Comment by dwright-adobe** [comment]
Hi @toddhaser ,
I recreated the prototypes using the current version of at.js (v2.10.2). All of the examples, work. One thing that is different though, is that parameters are now passed in the payload of a POST request, instead of as query string parameters of a GET request as they were with at.js 1.3. I will update the screenshots to clarify where you need to look.

**Comment by thetjhaze** [comment]
Thank you @dwright-adobe !
